<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'city'           => 'Milano Malpensa',
                'country'        => 'Italia',
                'iata_code'      => 'MXP',
                'flag_emoji'     => '🇮🇹',
                'price_from'     => 19.99,
                'color_from'     => '#1A5276',
                'color_to'       => '#2E86C1',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '1h 30m',
                'description_it' => 'Collegamento diretto con la capitale economica d\'Italia. Da Malpensa, metro e treno portano in centro Milano in 40 minuti. Da non perdere: Duomo, Brera, Navigli e l\'Ultima Cena di Leonardo.',
                'description_en' => 'Direct link to Italy\'s economic capital. From Malpensa, metro and train reach Milan city centre in 40 minutes. Must-see: the Duomo, Brera, Navigli and Leonardo\'s Last Supper.',
                'highlights_it'  => 'Duomo di Milano · Pinacoteca di Brera · Navigli · Expo 2015 legacy',
                'hotel_link'     => 'https://www.booking.com/city/it/milan.it.html',
                'sort_order'     => 1,
            ],
            [
                'city'           => 'Roma Fiumicino',
                'country'        => 'Italia',
                'iata_code'      => 'FCO',
                'flag_emoji'     => '🇮🇹',
                'price_from'     => 24.99,
                'color_from'     => '#7D3C98',
                'color_to'       => '#A569BD',
                'airlines_string'=> 'ITA Airways',
                'flight_duration'=> '1h 15m',
                'description_it' => 'La Capitale è a poco più di un\'ora di volo da Reggio Calabria. ITA Airways opera voli quotidiani su Fiumicino con coincidenze internazionali. Roma offre il Colosseo, i Musei Vaticani e la Fontana di Trevi.',
                'description_en' => 'The Italian capital is just over an hour\'s flight from Reggio Calabria. ITA Airways operates daily flights with international connections. Rome offers the Colosseum, Vatican Museums and Trevi Fountain.',
                'highlights_it'  => 'Colosseo · Musei Vaticani · Fontana di Trevi · Piazza Navona',
                'hotel_link'     => 'https://www.booking.com/city/it/rome.it.html',
                'sort_order'     => 2,
            ],
            [
                'city'           => 'Londra Stansted',
                'country'        => 'Gran Bretagna',
                'iata_code'      => 'STN',
                'flag_emoji'     => '🇬🇧',
                'price_from'     => 34.99,
                'color_from'     => '#1A5276',
                'color_to'       => '#0D2B4B',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '3h 00m',
                'description_it' => 'Vola a Londra con Ryanair da Reggio Calabria. Da Stansted, il treno National Express raggiunge Liverpool Street in 47 minuti. Ideal per la comunità calabrese in UK e per i turisti diretti a Londra.',
                'description_en' => 'Fly to London with Ryanair from Reggio Calabria. From Stansted, the National Express train reaches Liverpool Street in 47 minutes. Ideal for the Calabrian community in the UK.',
                'highlights_it'  => 'Tower of London · Tate Modern · Borough Market · West End',
                'hotel_link'     => 'https://www.booking.com/city/gb/london.it.html',
                'sort_order'     => 3,
            ],
            [
                'city'           => 'Barcellona El Prat',
                'country'        => 'Spagna',
                'iata_code'      => 'BCN',
                'flag_emoji'     => '🇪🇸',
                'price_from'     => 29.99,
                'color_from'     => '#C0392B',
                'color_to'       => '#E74C3C',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '2h 30m',
                'description_it' => 'Barcellona raggiungibile in meno di 3 ore da Reggio Calabria. La metropoli catalana offre l\'architettura di Gaudí, le Ramblas, il Barrio Gótico e spiagge urbane sul Mediterraneo. L\'aeroporto di El Prat è collegato in metro al centro.',
                'description_en' => 'Barcelona reachable in under 3 hours from Reggio Calabria. The Catalan metropolis offers Gaudí architecture, Las Ramblas, the Gothic Quarter and urban beaches on the Mediterranean.',
                'highlights_it'  => 'Sagrada Família · Park Güell · Barrio Gótico · Barceloneta',
                'hotel_link'     => 'https://www.booking.com/city/es/barcelona.it.html',
                'sort_order'     => 4,
            ],
            [
                'city'           => 'Berlino Brandenburg',
                'country'        => 'Germania',
                'iata_code'      => 'BER',
                'flag_emoji'     => '🇩🇪',
                'price_from'     => 39.99,
                'color_from'     => '#1C2833',
                'color_to'       => '#2C3E50',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '3h 00m',
                'description_it' => 'Berlino è raggiungibile direttamente da Reggio Calabria con Ryanair. La capitale tedesca è la più grande città dell\'UE e offre musei di classe mondiale, vita notturna leggendaria e una storia moderna unica. Dal BER, S-Bahn fino al centro in 30 minuti.',
                'description_en' => 'Berlin is reachable directly from Reggio Calabria with Ryanair. Germany\'s capital is the EU\'s largest city with world-class museums and legendary nightlife.',
                'description_de' => 'Berlin ist direkt von Reggio Calabria mit Ryanair erreichbar. Deutschlands Hauptstadt mit weltklasse Museen und legendärem Nachtleben.',
                'highlights_it'  => 'Porta di Brandeburgo · Pergamon Museum · Muro di Berlino · Reichstag',
                'hotel_link'     => 'https://www.booking.com/city/de/berlin.it.html',
                'sort_order'     => 5,
            ],
            [
                'city'           => 'Parigi Beauvais',
                'country'        => 'Francia',
                'iata_code'      => 'BVA',
                'flag_emoji'     => '🇫🇷',
                'price_from'     => 32.99,
                'color_from'     => '#1A3A5C',
                'color_to'       => '#2471A3',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '2h 45m',
                'description_it' => 'Parigi raggiungibile da Reggio Calabria via Beauvais con Ryanair. Dall\'aeroporto Beauvais-Tillé il bus navetta porta a Porte Maillot in 75 minuti. La Città della Luce offre la Torre Eiffel, il Louvre e la gastronomia francese.',
                'description_en' => 'Paris reachable from Reggio Calabria via Beauvais with Ryanair. From Beauvais-Tillé airport the shuttle bus reaches Porte Maillot in 75 minutes.',
                'description_fr' => 'Paris accessible depuis Reggio Calabria via Beauvais avec Ryanair. Depuis l\'aéroport Beauvais-Tillé, la navette rejoint Porte Maillot en 75 minutes.',
                'highlights_it'  => 'Torre Eiffel · Louvre · Montmartre · Versailles',
                'hotel_link'     => 'https://www.booking.com/city/fr/paris.it.html',
                'sort_order'     => 6,
            ],
            [
                'city'           => 'Bologna',
                'country'        => 'Italia',
                'iata_code'      => 'BLQ',
                'flag_emoji'     => '🇮🇹',
                'price_from'     => 22.99,
                'color_from'     => '#7E5109',
                'color_to'       => '#D4AC0D',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '1h 20m',
                'description_it' => 'Bologna La Dotta, La Rossa, La Grassa: la città dei portici Patrimonio UNESCO offre la cucina italiana più celebrata al mondo — tortellini, tagliatelle al ragù, mortadella. L\'aeroporto Marconi è collegato in treno al centro.',
                'description_en' => 'Bologna: the city of UNESCO porticoes offers Italy\'s most celebrated cuisine — tortellini, tagliatelle al ragù, mortadella. Marconi airport is connected by train to the centre.',
                'highlights_it'  => 'Portico di San Luca · Piazza Maggiore · Due Torri · Osterie storiche',
                'hotel_link'     => 'https://www.booking.com/city/it/bologna.it.html',
                'sort_order'     => 7,
            ],
            [
                'city'           => 'Torino',
                'country'        => 'Italia',
                'iata_code'      => 'TRN',
                'flag_emoji'     => '🇮🇹',
                'price_from'     => 21.99,
                'color_from'     => '#1F618D',
                'color_to'       => '#2980B9',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '1h 35m',
                'description_it' => 'Torino è la prima capitale d\'Italia, città del Risorgimento, della Fiat e del Museo Egizio — il più importante fuori Cairo. La Mole Antonelliana è il simbolo di una città elegante e cosmopolita, con vista sulle Alpi innevate.',
                'description_en' => 'Turin is Italy\'s first capital, home to the Egyptian Museum — the most important outside Cairo — and the Mole Antonelliana, with views of the snow-capped Alps.',
                'highlights_it'  => 'Museo Egizio · Mole Antonelliana · Palazzo Reale · Vista sulle Alpi',
                'hotel_link'     => 'https://www.booking.com/city/it/turin.it.html',
                'sort_order'     => 8,
            ],
            [
                'city'           => 'Milano Linate',
                'country'        => 'Italia',
                'iata_code'      => 'LIN',
                'flag_emoji'     => '🇮🇹',
                'price_from'     => 23.99,
                'color_from'     => '#145A32',
                'color_to'       => '#1E8449',
                'airlines_string'=> 'ITA Airways',
                'flight_duration'=> '1h 25m',
                'description_it' => 'Milano Linate è il City Airport di Milano: a soli 7 km dal centro, collegato in metro M4 in 12 minuti. ITA Airways opera voli quotidiani da Reggio Calabria. L\'aeroporto più comodo per chi lavora in città.',
                'description_en' => 'Milan Linate is Milan\'s City Airport: just 7 km from the centre, connected by metro M4 in 12 minutes. ITA Airways operates daily flights from Reggio Calabria.',
                'highlights_it'  => 'Centro Milano in 12 min · Business district · Corso Como · Design Quarter',
                'hotel_link'     => 'https://www.booking.com/city/it/milan.it.html',
                'sort_order'     => 9,
            ],
            [
                'city'           => 'Napoli',
                'country'        => 'Italia',
                'iata_code'      => 'NAP',
                'flag_emoji'     => '🇮🇹',
                'price_from'     => 18.99,
                'color_from'     => '#922B21',
                'color_to'       => '#CB4335',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '55m',
                'description_it' => 'Napoli è a meno di un\'ora di volo da Reggio Calabria — la rotta più breve in partenza da REG. Patrimonio UNESCO per il centro storico, pizza Margherita originale, Pompeii, Costiera Amalfitana e il Vesuvio.',
                'description_en' => 'Naples is under an hour\'s flight from Reggio Calabria — the shortest route from REG. UNESCO heritage centre, original Margherita pizza, Pompeii, Amalfi Coast and Vesuvius.',
                'highlights_it'  => 'Pizza Margherita · Pompeii · Costiera Amalfitana · Museo Archeologico',
                'hotel_link'     => 'https://www.booking.com/city/it/naples.it.html',
                'sort_order'     => 10,
            ],
            [
                'city'           => 'Bergamo Orio al Serio',
                'country'        => 'Italia',
                'iata_code'      => 'BGY',
                'flag_emoji'     => '🇮🇹',
                'price_from'     => 17.99,
                'color_from'     => '#1B4F72',
                'color_to'       => '#2471A3',
                'airlines_string'=> 'Ryanair',
                'flight_duration'=> '1h 35m',
                'description_it' => 'L\'aeroporto di Bergamo Orio al Serio è il secondo hub Ryanair in Italia dopo Roma Ciampino. Con bus navetta si raggiunge Milano in 1 ora o Bergamo Alta in 15 minuti. Bergamo Alta è uno dei borghi medievali più belli d\'Italia.',
                'description_en' => 'Bergamo Orio al Serio is Ryanair\'s second Italian hub. Shuttle bus reaches Milan in 1 hour or Bergamo Alta (a stunning medieval hilltop town) in 15 minutes.',
                'highlights_it'  => 'Bergamo Alta · Città Muraria UNESCO · Milano in 1h · Lago di Como',
                'hotel_link'     => 'https://www.booking.com/city/it/bergamo.it.html',
                'sort_order'     => 11,
            ],
        ];

        foreach ($destinations as $dest) {
            Destination::updateOrCreate(['iata_code' => $dest['iata_code']], $dest);
        }

        $this->command->info('✅ Destinazioni inserite/aggiornate: ' . count($destinations));
    }
}
