---
deployment:
  tasks:
    - /bin/mkdir -p /home/aeroportorc/aerrc
    - /bin/cp -Rf $CPANEL_BASE_INSTALL_DIR/. /home/aeroportorc/aerrc/
    - /bin/cp -Rf $CPANEL_BASE_INSTALL_DIR/public/. /home/aeroportorc/public_html/
    - /bin/cp /home/aeroportorc/aerrc/public/index.cpanel.php /home/aeroportorc/public_html/index.php
    - /bin/chmod -R 775 /home/aeroportorc/aerrc/storage
    - /bin/chmod -R 775 /home/aeroportorc/aerrc/bootstrap/cache
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan config:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan route:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan view:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan db:seed --class=Database\\Seeders\\FlightScheduleSeeder --force
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan config:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan route:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan view:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/aeroportorc/aerrc/artisan optimize
    - /bin/ln -sfn /home/aeroportorc/aerrc/storage/app/public /home/aeroportorc/public_html/storage
